In [1]:
import numpy as np

In [2]:
v =  np.array([1,-1,2])
w = np.array([2,5,2])

In [3]:
print(v+w)

[3 4 4]


In [5]:
print(v*w)

[ 2 -5  4]


In [6]:
print(v-w)

[-1 -6  0]


In [8]:
#Scalar multiplication 
print(3*v)
print(-4*w)

[ 3 -3  6]
[ -8 -20  -8]


In [11]:
#length of vector
print(np.linalg.norm(v))

2.449489742783178


In [10]:
print(np.linalg.norm(w))

5.744562646538029


In [13]:
s = np.dot(v,w)
print(s)

1


In [16]:
p = np.array(([1,2],[4,5]))

In [17]:
print(p)

[[1 2]
 [4 5]]


In [20]:
q = np.array(([1,2],[6,7]))
s = p + q 
v = p - q
print(s)
print(v)

[[ 2  4]
 [10 12]]
[[ 0  0]
 [-2 -2]]


In [23]:
np.linalg.det(p)

-2.9999999999999996